spring:
  application:
    name: validation-example
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**

server:
  port: 8080


